import unittest
from unittest.mock import patch

from app.tools.site_pro.adapter import SiteAuditProAdapter


class _MockResponse:
    def __init__(self, url: str, status_code: int, text: str):
        self.url = url
        self.status_code = status_code
        self.text = text


HTML_HOME = """
<html><head>
<title>Home Page</title>
<meta name="description" content="Main page description">
<link rel="canonical" href="https://site.test/">
</head>
<body>
<h1>Home</h1>
<a href="/about">About us</a>
<a href="/blog">Read more</a>
<p>SEO audit platform test content for home page with useful terms about optimization and crawling.</p>
</body></html>
"""

HTML_ABOUT = """
<html><head>
<title>About Team</title>
<meta name="description" content="About page description">
</head>
<body>
<h1>About</h1>
<a href="/">Home</a>
<p>About team and company profile content with optimization services and strategy.</p>
</body></html>
"""

HTML_BLOG = """
<html><head>
<title>About Team</title>
<meta name="description" content="About page description">
</head>
<body>
<h1>Blog</h1>
<a href="/">Home</a>
<p>Blog article generated by AI assistant with neural content hints.</p>
</body></html>
"""


class SiteProAdapterTests(unittest.TestCase):
    def test_pipeline_and_duplicates(self):
        adapter = SiteAuditProAdapter()
        by_url = {
            "https://site.test": _MockResponse("https://site.test", 200, HTML_HOME),
            "https://site.test/about": _MockResponse("https://site.test/about", 200, HTML_ABOUT),
            "https://site.test/blog": _MockResponse("https://site.test/blog", 200, HTML_BLOG),
        }

        def fake_get(url, timeout=0, allow_redirects=True):
            key = url.rstrip("/")
            if key == "https://site.test":
                return by_url["https://site.test"]
            return by_url[key]

        with patch("requests.Session.get", side_effect=fake_get):
            normalized = adapter.run("https://site.test", mode="quick", max_pages=10)
            public = adapter.to_public_results(normalized)

        self.assertEqual(public["summary"]["total_pages"], 3)
        self.assertIn("pipeline", public)
        pipeline = public["pipeline"]
        self.assertTrue(len(pipeline["pagerank"]) > 0)
        self.assertTrue(len(pipeline["tf_idf"]) > 0)
        self.assertTrue(len(pipeline["topic_clusters"]) > 0)
        # About+Blog share duplicate title/description.
        self.assertTrue(len(pipeline["duplicates"]["title_groups"]) >= 1)
        self.assertTrue(len(pipeline["duplicates"]["description_groups"]) >= 1)


if __name__ == "__main__":
    unittest.main()
