import unittest
from unittest.mock import patch

from app.tools.site_pro.adapter import SiteAuditProAdapter


class _MockResponse:
    def __init__(self, url: str, status_code: int, text: str, reason: str = "OK"):
        self.url = url
        self.status_code = status_code
        self.text = text
        self.reason = reason


HTML_HOME = """
<html><head>
<title>Home Page</title>
<meta name="description" content="Main page description">
<link rel="canonical" href="https://site.test/">
</head>
<body>
<h1>Home</h1>
<a href="/about">About us</a>
<a href="/blog">Read more</a>
<p>SEO audit platform test content for home page with useful terms about optimization and crawling.</p>
</body></html>
"""

HTML_ABOUT = """
<html><head>
<title>About Team</title>
<meta name="description" content="About page description">
</head>
<body>
<h1>About</h1>
<a href="/">Home</a>
<p>About team and company profile content with optimization services and strategy.</p>
</body></html>
"""

HTML_BLOG = """
<html><head>
<title>About Team</title>
<meta name="description" content="About page description">
</head>
<body>
<h1>Blog</h1>
<a href="/">Home</a>
<p>Blog article generated by AI assistant with neural content hints.</p>
</body></html>
"""


def build_mock_public_result():
    adapter = SiteAuditProAdapter()
    by_url = {
        "https://site.test": _MockResponse("https://site.test", 200, HTML_HOME),
        "https://site.test/about": _MockResponse("https://site.test/about", 200, HTML_ABOUT),
        "https://site.test/blog": _MockResponse("https://site.test/blog", 200, HTML_BLOG),
    }

    def fake_get(url, timeout=0, allow_redirects=True):
        key = url.rstrip("/")
        if key == "https://site.test":
            return by_url["https://site.test"]
        return by_url[key]

    with patch("requests.Session.get", side_effect=fake_get):
        normalized = adapter.run("https://site.test", mode="quick", max_pages=10)
        return adapter.to_public_results(normalized)


class SiteProAdapterTests(unittest.TestCase):
    def test_detect_ai_markers_seopro_phrases(self):
        adapter = SiteAuditProAdapter()
        text = (
            "\u0412 \u0441\u043e\u0432\u0440\u0435\u043c\u0435\u043d\u043d\u043e\u043c \u043c\u0438\u0440\u0435 "
            "\u0432\u0430\u0436\u043d\u043e \u043f\u043e\u0434\u0447\u0435\u0440\u043a\u043d\u0443\u0442\u044c, "
            "\u0447\u0442\u043e \u0432 \u0446\u0435\u043b\u043e\u043c \u043c\u043e\u0436\u043d\u043e \u0441\u043a\u0430\u0437\u0430\u0442\u044c: "
            "\u0441\u043b\u0435\u0434\u0443\u0435\u0442 \u043e\u0442\u043c\u0435\u0442\u0438\u0442\u044c, "
            "\u0447\u0442\u043e \u043a\u0430\u043a \u0438\u0437\u0432\u0435\u0441\u0442\u043d\u043e, \u0440\u0435\u0448\u0435\u043d\u0438\u0435 \u043f\u0440\u0430\u0432\u0438\u043b\u044c\u043d\u043e\u0435."
        )
        count, markers = adapter._detect_ai_markers(text)
        self.assertGreaterEqual(count, 4)
        self.assertTrue(any(m == "\u043a\u0430\u043a \u0438\u0437\u0432\u0435\u0441\u0442\u043d\u043e" for m in markers))

    def test_detect_ai_markers_modern_llm_phrases(self):
        adapter = SiteAuditProAdapter()
        text = (
            "In this comprehensive guide, it is important to note that "
            "as an AI language model, I hope this helps. "
            "Feel free to ask for a step-by-step guide."
        )
        count, markers = adapter._detect_ai_markers(text)
        self.assertGreaterEqual(count, 4)
        self.assertTrue(any(m == "as an ai language model" for m in markers))

    def test_pipeline_and_duplicates(self):
        public = build_mock_public_result()

        self.assertEqual(public["summary"]["total_pages"], 3)
        self.assertIn("pipeline", public)
        pipeline = public["pipeline"]
        self.assertTrue(len(pipeline["pagerank"]) > 0)
        self.assertTrue(len(pipeline["tf_idf"]) > 0)
        self.assertTrue(len(pipeline["topic_clusters"]) > 0)
        # About+Blog share duplicate title/description.
        self.assertTrue(len(pipeline["duplicates"]["title_groups"]) >= 1)
        self.assertTrue(len(pipeline["duplicates"]["description_groups"]) >= 1)
        self.assertIn("metrics", pipeline)
        self.assertIn("avg_response_time_ms", pipeline["metrics"])
        self.assertIn("avg_readability_score", pipeline["metrics"])
        self.assertIn("avg_link_quality_score", pipeline["metrics"])
        self.assertIn("orphan_pages", pipeline["metrics"])

        for page in public["pages"]:
            self.assertIn("status_line", page)
            self.assertIn("recommendation", page)
            self.assertIn("orphan_page", page)
            self.assertIn("topic_hub", page)
            self.assertIn("canonical_status", page)
            self.assertIn("x_robots_tag", page)
            self.assertIn("structured_data", page)
            self.assertIn("images_optimization", page)
            self.assertIn("ai_marker_sample", page)

    def test_canonical_conflict_and_extended_hreflang_toggle(self):
        adapter = SiteAuditProAdapter()
        home = """
<html><head>
<title>Home</title>
<meta name="description" content="Home description">
<link rel="canonical" href="https://site.test/en">
<link rel="alternate" hreflang="en" href="https://site.test/en">
<link rel="alternate" hreflang="x-default" href="https://site.test/">
</head>
<body><h1>Home</h1><a href="/en">EN</a></body></html>
"""
        en = """
<html><head>
<title>EN</title>
<meta name="robots" content="noindex">
</head>
<body><h1>English</h1><a href="/">Home</a></body></html>
"""
        by_url = {
            "https://site.test": _MockResponse("https://site.test", 200, home),
            "https://site.test/en": _MockResponse("https://site.test/en", 200, en),
        }

        def fake_get(url, timeout=0, allow_redirects=True):
            key = url.rstrip("/")
            if key == "https://site.test":
                return by_url["https://site.test"]
            return by_url[key]

        with patch("requests.Session.get", side_effect=fake_get):
            normalized = adapter.run(
                "https://site.test",
                mode="quick",
                max_pages=5,
                extended_hreflang_checks=True,
            )
            public = adapter.to_public_results(normalized)

        home_row = next(p for p in public["pages"] if p["url"] == "https://site.test")
        issue_codes = {i["code"] for i in public["issues"] if i["url"] == "https://site.test"}
        self.assertIn("canonical_target_noindex", issue_codes)
        self.assertIn("hreflang_extended_check", issue_codes)
        self.assertTrue(any(str(x).startswith("missing_reciprocal:") for x in (home_row.get("hreflang_issues") or [])))

    def test_respects_max_pages_limit(self):
        adapter = SiteAuditProAdapter()
        by_url = {
            "https://site.test": _MockResponse("https://site.test", 200, HTML_HOME),
            "https://site.test/about": _MockResponse("https://site.test/about", 200, HTML_ABOUT),
            "https://site.test/blog": _MockResponse("https://site.test/blog", 200, HTML_BLOG),
        }

        def fake_get(url, timeout=0, allow_redirects=True):
            key = url.rstrip("/")
            if key == "https://site.test":
                return by_url["https://site.test"]
            return by_url[key]

        with patch("requests.Session.get", side_effect=fake_get):
            normalized = adapter.run("https://site.test", mode="quick", max_pages=2)
            public = adapter.to_public_results(normalized)

        self.assertLessEqual(public["summary"]["total_pages"], 2)


if __name__ == "__main__":
    unittest.main()
