"""
Word Report Generator
"""
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from typing import Dict, Any, List
from datetime import datetime
import os

from app.config import settings


class DOCXGenerator:
    """Генератор Word отчетов"""
    
    def __init__(self):
        self.reports_dir = settings.REPORTS_DIR
        os.makedirs(self.reports_dir, exist_ok=True)
    
    def _add_heading(self, doc, text: str, level: int = 1):
        """Добавляет заголовок"""
        heading = doc.add_heading(text, level=level)
        heading.alignment = WD_ALIGN_PARAGRAPH.LEFT
        return heading
    
    def _add_table(self, doc, headers: List[str], rows: List[List[Any]]):
        """Добавляет таблицу"""
        table = doc.add_table(rows=1, cols=len(headers))
        table.style = 'Light Grid Accent 1'
        table.alignment = WD_TABLE_ALIGNMENT.CENTER
        
        # Header row
        hdr_cells = table.rows[0].cells
        for i, header in enumerate(headers):
            hdr_cells[i].text = header
            # Make header bold
            for paragraph in hdr_cells[i].paragraphs:
                for run in paragraph.runs:
                    run.font.bold = True
        
        # Data rows
        for row_data in rows:
            row_cells = table.add_row().cells
            for i, value in enumerate(row_data):
                row_cells[i].text = str(value)
        
        return table
    
    def generate_site_analyze_report(self, task_id: str, data: Dict[str, Any]) -> str:
        """Генерирует отчет анализа сайта"""
        doc = Document()
        
        # Title
        title = doc.add_heading('SEO Site Analysis Report', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Basic info
        doc.add_paragraph(f"URL: {data.get('url', 'N/A')}")
        doc.add_paragraph(f"Pages Analyzed: {data.get('pages_analyzed', 0)}")
        doc.add_paragraph(f"Completed: {data.get('completed_at', 'N/A')}")
        
        doc.add_paragraph()  # Spacing
        
        # Results section
        self._add_heading(doc, 'Analysis Results', level=1)
        
        results = data.get('results', {})
        
        headers = ['Metric', 'Value', 'Status']
        rows = [
            ['Total Pages', results.get('total_pages', 0), 'OK'],
            ['Status', results.get('status', 'N/A'), 'OK'],
            ['Summary', results.get('summary', 'N/A'), 'OK']
        ]
        
        self._add_table(doc, headers, rows)
        
        # Footer
        doc.add_paragraph()
        footer = doc.add_paragraph(f"Generated by SEO Tools Platform on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer.runs[0].font.size = Pt(8)
        footer.runs[0].font.color.rgb = RGBColor(128, 128, 128)
        
        # Save
        filepath = os.path.join(self.reports_dir, f"{task_id}.docx")
        doc.save(filepath)
        return filepath
    
    def generate_robots_report(self, task_id: str, data: Dict[str, Any]) -> str:
        """Генерирует отчет robots.txt"""
        doc = Document()
        
        title = doc.add_heading('Robots.txt Analysis Report', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        doc.add_paragraph(f"URL: {data.get('url', 'N/A')}")
        
        results = data.get('results', {})
        doc.add_paragraph(f"Robots.txt Found: {'Yes' if results.get('robots_txt_found') else 'No'}")
        
        # Footer
        doc.add_paragraph()
        footer = doc.add_paragraph(f"Generated by SEO Tools Platform on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer.runs[0].font.size = Pt(8)
        footer.runs[0].font.color.rgb = RGBColor(128, 128, 128)
        
        filepath = os.path.join(self.reports_dir, f"{task_id}.docx")
        doc.save(filepath)
        return filepath
    
    def generate_sitemap_report(self, task_id: str, data: Dict[str, Any]) -> str:
        """Генерирует отчет sitemap"""
        doc = Document()
        
        title = doc.add_heading('Sitemap Validation Report', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        doc.add_paragraph(f"URL: {data.get('url', 'N/A')}")
        
        results = data.get('results', {})
        doc.add_paragraph(f"Valid: {'Yes' if results.get('valid') else 'No'}")
        doc.add_paragraph(f"URLs Count: {results.get('urls_count', 0)}")
        
        # Footer
        doc.add_paragraph()
        footer = doc.add_paragraph(f"Generated by SEO Tools Platform on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer.runs[0].font.size = Pt(8)
        footer.runs[0].font.color.rgb = RGBColor(128, 128, 128)
        
        filepath = os.path.join(self.reports_dir, f"{task_id}.docx")
        doc.save(filepath)
        return filepath
    
    def generate_render_report(self, task_id: str, data: Dict[str, Any]) -> str:
        """Генерирует отчет аудита рендеринга"""
        doc = Document()
        
        title = doc.add_heading('Render Audit Report', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        doc.add_paragraph(f"URL: {data.get('url', 'N/A')}")
        
        results = data.get('results', {})
        doc.add_paragraph(f"JS Render Difference: {'Yes' if results.get('js_render_diff') else 'No'}")
        
        # Footer
        doc.add_paragraph()
        footer = doc.add_paragraph(f"Generated by SEO Tools Platform on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer.runs[0].font.size = Pt(8)
        footer.runs[0].font.color.rgb = RGBColor(128, 128, 128)
        
        filepath = os.path.join(self.reports_dir, f"{task_id}.docx")
        doc.save(filepath)
        return filepath
    
    def generate_mobile_report(self, task_id: str, data: Dict[str, Any]) -> str:
        """Генерирует отчет мобильной проверки"""
        doc = Document()
        
        title = doc.add_heading('Mobile Compatibility Report', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        doc.add_paragraph(f"URL: {data.get('url', 'N/A')}")
        
        results = data.get('results', {})
        devices = results.get('devices_tested', [])
        
        self._add_heading(doc, 'Devices Tested', level=1)
        for device in devices:
            doc.add_paragraph(device, style='List Bullet')
        
        # Footer
        doc.add_paragraph()
        footer = doc.add_paragraph(f"Generated by SEO Tools Platform on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer.runs[0].font.size = Pt(8)
        footer.runs[0].font.color.rgb = RGBColor(128, 128, 128)
        
        filepath = os.path.join(self.reports_dir, f"{task_id}.docx")
        doc.save(filepath)
        return filepath
    
    def generate_bot_report(self, task_id: str, data: Dict[str, Any]) -> str:
        """Генерирует отчет проверки ботов"""
        doc = Document()
        
        title = doc.add_heading('Bot Accessibility Report', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        doc.add_paragraph(f"URL: {data.get('url', 'N/A')}")
        
        results = data.get('results', {})
        bots = results.get('bots_checked', [])
        
        self._add_heading(doc, 'Bots Checked', level=1)
        for bot in bots:
            doc.add_paragraph(bot, style='List Bullet')
        
        # Footer
        doc.add_paragraph()
        footer = doc.add_paragraph(f"Generated by SEO Tools Platform on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer.runs[0].font.size = Pt(8)
        footer.runs[0].font.color.rgb = RGBColor(128, 128, 128)
        
        filepath = os.path.join(self.reports_dir, f"{task_id}.docx")
        doc.save(filepath)
        return filepath
    
    def generate_report(self, task_id: str, task_type: str, data: Dict[str, Any]) -> str:
        """Генерирует отчет в зависимости от типа задачи"""
        generators = {
            'site_analyze': self.generate_site_analyze_report,
            'robots_check': self.generate_robots_report,
            'sitemap_validate': self.generate_sitemap_report,
            'render_audit': self.generate_render_report,
            'mobile_check': self.generate_mobile_report,
            'bot_check': self.generate_bot_report
        }
        
        generator = generators.get(task_type, self.generate_site_analyze_report)
        return generator(task_id, data)


# Singleton
docx_generator = DOCXGenerator()
